name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        env:
          NODE_ENV: production
        run: |
          npm run build
          mkdir -p public
          cp -r build/* public/
          cp index.html public/

      - name: Deploy to GitHub Pages
        uses: actions/github-pages@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: ./public